# Generated by Django 3.2.14 on 2022-07-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_jobpostactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='apply_user',
            field=models.BooleanField(default=1, verbose_name='지원상태'),
            preserve_default=False,
        ),
    ]
