# Generated by Django 3.2.14 on 2022-07-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_jobpost_apply_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='apply_user',
            field=models.CharField(max_length=30, verbose_name='지원상태'),
        ),
    ]
