# Generated by Django 3.2.14 on 2022-07-22 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_jobpost_apply_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApllyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_user', models.CharField(max_length=30, verbose_name='지원상태')),
                ('job_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.jobpost')),
            ],
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='apply_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.apllyuser'),
        ),
    ]
