# Generated by Django 3.2.14 on 2022-07-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20220722_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='apply_user',
        ),
    ]
